### PR TITLE
add full response to error message

### PR DESCRIPTION
**Pull request by volkhin**
I started using your module and got first error - and it was hard to find it without full response from server. Actual meaning of 404 was missing argument to /droplets/new, hope it helps somebody else.

### CODE REVIEW

**Comment by volkhin** [comment]
Yay! I'm so happy you've merged it!

**Comment by ahmontero** [comment]
Sorry for the delay, but I have been busy!

**Comment by volkhin** [comment]
No problem, I'm happy to help!

**Comment by ahmontero** [comment]
;)

**Pull request merged**
